base_url = "https://ratysz.github.io"

theme = "Zulma"

highlight_code = true

highlight_theme = "material-dark"

compile_sass = true

taxonomies = [
    {name = "tags"},
]

[extra]
zulma_theme = "slate"
zulma_brand = {text = "Home"}
zulma_menu = [
    {url = "$BASE_URL/article", name = "Articles"},
    {url = "$BASE_URL/tags", name = "Tags"},
]